name: PyTest
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install -e .[test]

      - name: Run test suite
        run: |
          pytest --cov=hcl_model --cov-report=xml

      - name: Publish code coverage
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
